// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP mpbart_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpparma_hello_world());
    return __result;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP mpbart_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    __result = Rcpp::wrap(rcpparma_outerproduct(x));
    return __result;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP mpbart_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    __result = Rcpp::wrap(rcpparma_innerproduct(x));
    return __result;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP mpbart_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    __result = Rcpp::wrap(rcpparma_bothproducts(x));
    return __result;
END_RCPP
}
// rcpparma_rmnpMDA
Rcpp::List rcpparma_rmnpMDA(arma::mat const trainx, arma::mat const testx, arma::mat sigmai, arma::mat V, int n, int n_dim, arma::ivec y, int pn_cov, int nu, int testn, int pndraws, int pburn, int pntrees, double pkfac, double ppbd, double ppb, double palpha, double pbetap, int pnc, int savesigma, int minobsnode);
RcppExport SEXP mpbart_rcpparma_rmnpMDA(SEXP trainxSEXP, SEXP testxSEXP, SEXP sigmaiSEXP, SEXP VSEXP, SEXP nSEXP, SEXP n_dimSEXP, SEXP ySEXP, SEXP pn_covSEXP, SEXP nuSEXP, SEXP testnSEXP, SEXP pndrawsSEXP, SEXP pburnSEXP, SEXP pntreesSEXP, SEXP pkfacSEXP, SEXP ppbdSEXP, SEXP ppbSEXP, SEXP palphaSEXP, SEXP pbetapSEXP, SEXP pncSEXP, SEXP savesigmaSEXP, SEXP minobsnodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const >::type trainx(trainxSEXP);
    Rcpp::traits::input_parameter< arma::mat const >::type testx(testxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigmai(sigmaiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_dim(n_dimSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type pn_cov(pn_covSEXP);
    Rcpp::traits::input_parameter< int >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type testn(testnSEXP);
    Rcpp::traits::input_parameter< int >::type pndraws(pndrawsSEXP);
    Rcpp::traits::input_parameter< int >::type pburn(pburnSEXP);
    Rcpp::traits::input_parameter< int >::type pntrees(pntreesSEXP);
    Rcpp::traits::input_parameter< double >::type pkfac(pkfacSEXP);
    Rcpp::traits::input_parameter< double >::type ppbd(ppbdSEXP);
    Rcpp::traits::input_parameter< double >::type ppb(ppbSEXP);
    Rcpp::traits::input_parameter< double >::type palpha(palphaSEXP);
    Rcpp::traits::input_parameter< double >::type pbetap(pbetapSEXP);
    Rcpp::traits::input_parameter< int >::type pnc(pncSEXP);
    Rcpp::traits::input_parameter< int >::type savesigma(savesigmaSEXP);
    Rcpp::traits::input_parameter< int >::type minobsnode(minobsnodeSEXP);
    __result = Rcpp::wrap(rcpparma_rmnpMDA(trainx, testx, sigmai, V, n, n_dim, y, pn_cov, nu, testn, pndraws, pburn, pntrees, pkfac, ppbd, ppb, palpha, pbetap, pnc, savesigma, minobsnode));
    return __result;
END_RCPP
}
