# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('mpbart_rcpparma_hello_world', PACKAGE = 'mpbart')
}

rcpparma_outerproduct <- function(x) {
    .Call('mpbart_rcpparma_outerproduct', PACKAGE = 'mpbart', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('mpbart_rcpparma_innerproduct', PACKAGE = 'mpbart', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('mpbart_rcpparma_bothproducts', PACKAGE = 'mpbart', x)
}

rcpparma_rmnpMDA <- function(trainx, testx, sigmai, V, n, n_dim, y, pn_cov, nu, testn, pndraws, pburn, pntrees, pkfac, ppbd, ppb, palpha, pbetap, pnc, savesigma, minobsnode) {
    .Call('mpbart_rcpparma_rmnpMDA', PACKAGE = 'mpbart', trainx, testx, sigmai, V, n, n_dim, y, pn_cov, nu, testn, pndraws, pburn, pntrees, pkfac, ppbd, ppb, palpha, pbetap, pnc, savesigma, minobsnode)
}

